version: "3.2"
services:
  app:
    container_name: appdev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env      
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}

  mysql:
    container_name: mysqldev           
    image: mysql:5.7
    env_file:
      - .env  
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_HOST: $DB_HOST
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - 3306
    restart: unless-stopped     
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: mysql -u -p --user=$$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD --host=localhost -e 'SHOW DATABASES;'
      timeout: 5s
      retries: 5           

  phpmyadmin:
    container_name: phpmyadmindev  
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 5426:80
    restart: always      